Throw a better error is the ES_RANK_CLOUD_ID env var is missing
Previously you'd get a TypeError when we tried to pass `undefined` into
the new Elasticsearch client:

    TypeError: Cannot read properties of undefined (reading 'split')

      15 |
      16 |   if (!rankClient) {
    > 17 |     rankClient = new Client({
         |                  ^
      18 |       cloud: {
      19 |         id: ES_RANK_CLOUD_ID!,
      20 |       },

      at new Client (node_modules/@elastic/elasticsearch/index.js:56:40)
      at Object.getRankClient (services/elasticsearch.ts:17:18)
      at services/search-templates.ts:14:26
      at step (services/search-templates.ts:52:23)
      at Object.next (services/search-templates.ts:33:53)
      at services/search-templates.ts:27:71
      at Object.<anonymous>.__awaiter (services/search-templates.ts:23:12)
      at listIndices (services/search-templates.ts:62:12)
      at Object.<anonymous> (services/search-templates.ts:72:25)