Add explicit errors for missing ES credentials
Previously you'd get a slightly oblique error:

    ResponseError: security_exception: [security_exception] Reason: missing authentication credentials for REST request [/_cat/indices?h=index]

      at Unzip.onBody [as cb] (node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)

which didn't make it obvious if the credentials were missing, or if so,
which of the variables was unset.